config-app:
  id: ${random.uuid}
  msg: cliente service ${spring.application.name}


spring:
  profiles:
    include:
      - kafka-cloud

  messages:
    basename: ${spring.cloud.config.uri}/${spring.application.name}-messages
    fallback-to-system-locale: false
