config-app:
  id: ${random.uuid}
  msg: cliente service ${spring.application.name}


spring:
  profiles:
    include:
      - kafka-cloud

  messages:
    basename: "messages,${spring.application.name}-messages"
    fallback-to-system-locale: false
