#SPRING_PROFILES_ACTIVE=application-default,application-de,default

config-app:
  msg: cloud -> Mensagem do service ${spring.application.name} ->  ALTERADO 20h09

spring:
  profiles:
    include:
      - kafka-cloud
      - oracle